---

dist: jammy
language: python
python: "3.10"

env: PIPENV_IGNORE_VIRTUALENVS=1 # See https://travis-ci.community/t/issue-pipenv-check-fails-due-to-numpy/2120/2

before_install: pip install pipenv
install:
  - pipenv sync --dev
  - pipenv check
script: pipenv run ansible-lint -p setup.yml -vv
