---

dist: xenial
language: python
python: "3.7"

env: PIPENV_IGNORE_VIRTUALENVS=1 # See https://travis-ci.community/t/issue-pipenv-check-fails-due-to-numpy/2120/2

before_install: pip install pipenv
install:
  - pipenv install --dev
  - pipenv check
script: pipenv run ansible-lint setup.yml
