[project]
name = ""
version = "0.0.1"
requires-python = "~=3.13.0"
dependencies = ["ansible==11.8.0"]

[dependency-groups]
dev = ["ansible-lint==25.6.1"]

[tool.uv]
package = false
environments = ["platform_system != 'Windows'"]


[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
