#!/usr/bin/env -S ansible-playbook --connection local

- hosts: localhost
  handlers:
    - name: Handlers | Import tasks
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Debug | Display Ansible Gathered facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: ['never', 'debug']

    - name: XDG user directories | Import tasks
      ansible.builtin.import_tasks: tasks/xdg_user_directories.yml
      tags: ['xdg_user_directories']

    - name: Nftables | Import tasks
      ansible.builtin.import_tasks: tasks/nftables.yml
      tags: ['nftables']

    - name: wpa_supplicant | Import tasks
      ansible.builtin.import_tasks: tasks/wpa_supplicant.yml
      tags: ['wpa_supplicant']

    - name: Sound | Import tasks
      ansible.builtin.import_tasks: tasks/sound.yml
      tags: ['sound']

    - name: Dotfiles | Import tasks
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']

    - name: Fonts | Import tasks
      ansible.builtin.import_tasks: tasks/fonts.yml
      tags: ['fonts']

    - name: Packages | Import tasks
      ansible.builtin.import_tasks: tasks/packages.yml
      tags: ['packages']

    - name: GnuPG | Import tasks
      ansible.builtin.import_tasks: tasks/gnupg.yml
      tags: ['gnupg']

    - name: Google Chrome | Import tasks
      ansible.builtin.import_tasks: tasks/google-chrome.yml
      tags: ['google-chrome']

    - name: Wireshark | Import tasks
      ansible.builtin.import_tasks: tasks/wireshark.yml
      tags: ['wireshark']

    - name: YubiKey | Import tasks
      ansible.builtin.import_tasks: tasks/yubikey.yml
      tags: ['yubikey']
