#!/usr/bin/env -S ansible-playbook --connection local

- name: Setup workstation
  hosts: localhost
  handlers:
    - name: Handlers | Import tasks
      ansible.builtin.import_tasks: tasks/handlers.yml
      become: true
  tasks:
    - name: Debug | Display Ansible Gathered facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: ['never', 'debug']

    - name: XDG user directories | Import tasks
      ansible.builtin.import_tasks: tasks/xdg_user_directories.yml
      tags: ['xdg_user_directories']

    - name: Facts | Compute Ansible Facts
      ansible.builtin.import_tasks: tasks/compute_ansible_facts.yml
      tags: ['compute_ansible_facts']

    - name: Firewall | Import tasks
      ansible.builtin.import_tasks: tasks/firewall.yml
      become: true
      tags: ['firewall']

    - name: Network | Import tasks
      ansible.builtin.import_tasks: tasks/network.yml
      become: true
      tags: ['network']

    - name: Sound | Import tasks
      ansible.builtin.import_tasks: tasks/sound.yml
      become: true
      tags: ['sound']

    - name: Dotfiles | Import tasks
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']

    - name: Fonts | Import tasks
      ansible.builtin.import_tasks: tasks/fonts.yml
      become: true
      tags: ['fonts']

    - name: Packages | Import tasks
      ansible.builtin.import_tasks: tasks/packages.yml
      become: true
      tags: ['packages']

    - name: GnuPG | Import tasks
      ansible.builtin.import_tasks: tasks/gnupg.yml
      become: true
      tags: ['gnupg']

    - name: Google Chrome | Import tasks
      ansible.builtin.import_tasks: tasks/google-chrome.yml
      become: true
      tags: ['google-chrome']

    - name: Wireshark | Import tasks
      ansible.builtin.import_tasks: tasks/wireshark.yml
      become: true
      tags: ['wireshark']

    - name: YubiKey | Import tasks
      ansible.builtin.import_tasks: tasks/yubikey.yml
      become: true
      tags: ['yubikey']
