---

- hosts: localhost
  connection: local
  tasks:
    - tags: ['pacman']
      import_tasks: tasks/configure/pacman.yml

    - tags: ['packages']
      import_tasks: tasks/install/packages.yml

    - tags: ['dotfiles']
      import_tasks: tasks/install/dotfiles.yml

    - tags: ['aur']
      import_tasks: tasks/install/aur.yml

    - tags: ['desktop']
      import_tasks: tasks/configure/desktop.yml

    - tags: ['system']
      import_tasks: tasks/configure/system.yml

    - tags: ['network', 'wifi']
      import_tasks: tasks/configure/wifi.yml

    - tags: ['firewall']
      import_tasks: tasks/configure/firewall.yml

    - tags: ['chrome']
      import_tasks: tasks/configure/chrome.yml
