---

- tags: ['vimplug']
  block:
    - name: VimPlug | Create autoload directory
      file:
        path: "{{ ansible_user_dir }}/.vim/autoload/"
        state: directory
        recurse: yes

    - name: Install Vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_user_dir }}/.vim/autoload/plug.vim"


- name: Clone Antigen repo
  tags: ['antigen', 'zsh']
  git:
    repo: https://github.com/zsh-users/antigen.git
    dest: "{{ ansible_user_dir }}/.antigen"
    version: master


- name: Link config file
  find:
    paths: ./files/dotfiles
    hidden: yes
    recurse: yes
  register: dotfiles_found

- name: Dotfiles | Create directories before linking
  file:
    path: "{{ ansible_user_dir }}/{{ item.path | relpath('files/dotfiles') | dirname }}"
    mode: 0750
    state: directory
    recurse: yes
  with_items: "{{ dotfiles_found.files }}"
  when: (item.path | relpath('files/dotfiles') | dirname)

- name: Dotfiles | Link files
  file:
    src: "{{ item.path | realpath }}"
    dest: "{{ ansible_user_dir }}/{{ item.path | relpath('files/dotfiles') }}"
    mode: 0640
    state: link
    force: yes
  with_items: "{{ dotfiles_found.files }}"


- debug:
    msg: "Don't forget to run `antigen selfupdate` and `antigen update`"

- debug:
    msg: "Don't forget to run `vim +PlugInstall +PlugUpdate`"
