---

- name: Facts | Lookup for XDG Environment variables
  ansible.builtin.set_fact:
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_user_dir + '/.config', True) }}"
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') | default(ansible_user_dir + '/.local/share', True) }}"
  tags: ['always']

- name: Facts | Print Computed Ansible Facts
  ansible.builtin.debug:
    msg:
      - "XDG_CONFIG_HOME: {{ xdg_config_home }}"
      - "XDG_DATA_HOME: {{ xdg_data_home }}"
  tags: ['never', 'debug']
