---

- name: Nftables | Installation
  ansible.builtin.package:
    name: iptables-nft
    state: present

- name: Nftables | Copy configuration file
  ansible.builtin.template:
    src: files/etc_nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: "0600"
    validate: /usr/bin/nft --check --file %s
  notify:
    - Nftables | Restart service

- name: Nftables | Ensure service is activated
  ansible.builtin.service:
    name: nftables
    enabled: true
