---

- name: Fonts | Install packages
  become: true
  ansible.builtin.package:
    name:
      - noto-fonts-emoji
      - terminus-font
      - ttf-bitstream-vera
      - ttf-dejavu
      - ttf-droid
      - ttf-font-awesome
      - ttf-freefont
      - ttf-inconsolata
      - ttf-liberation
      - ttf-linux-libertine
