---

- name: Google Chrome | Install
  become: false
  kewlfft.aur.aur:
    use: paru
    name:
      - google-chrome

- name: Google Chrome | Configure default extensions
  ansible.builtin.copy:
    content: "{ \"external_update_url\": \"https://clients2.google.com/service/update2/crx\" }"
    dest: "/opt/google/chrome/default_apps/{{ item }}.json"
    mode: "0644"
  loop:
    - gcbommkclmclpchllfjekcdonpmejbdp # HTTPS Everywhere
    - pkehgijcmpdhfbdbbnkijodmdjhbjlgp # Privacy Badger
    - cjpalhdlnbpafiamejdnhcphjbkeiagm # uBlock Origin
    - mfidmkgnfgnkihnjeklbekckimkipmoe # Flashcontrol
    - eiadekoaikejlgdbkbdfeijglgfdalml # WebRTC Leak Prevent
    - dbepggeogbaibhgnhhndojpepiihcmeb # Vimium
