---

- name: Packages | Update cache
  community.general.pacman:
    update_cache: true

- name: Packages | Install
  ansible.builtin.package:
    name:
        # Dev common
      - bandit
      - base-devel
      - bat
      - certbot
      - certbot-dns-ovh
      - clang
      - cmake
      - code
      - ctags
      - difftastic
      - fd
      - flake8
      - fzf
      - git
      - git-lfs
      - go
      - inotify-tools
      - jdk-openjdk
      - mono
      - mypy
      - nodejs
      - npm
      - powerline
      - powerline-vim
      - python-black
      - python-isort
      - python-pylint
      - rust
      - starship
      - the_silver_searcher
      - tmux

        # Hardware
      - fwupd
      - lshw

        # Iphone
      - usbmuxd # USB Tethering

        # Media
      - gimp
      - imagemagick
      - usbutils
      - vlc

        # Monitoring
      - glances
      - htop

        # Network
      - curl
      - dnsutils
      - mtr
      - nmap
      - openbsd-netcat
      - openssh
      - socat
      - tcpdump
      - wget
      - whois

        # Office
      - borgmatic
      - brightnessctl
      - hunspell
      - hunspell-en_us
      - hunspell-fr
      - keepassxc
      - libfido2
      - libreoffice-fresh
      - pandoc
      - texlive-core
      - texlive-fontsextra
      - texlive-latexextra
      - texlive-pictures
      - thunderbird
      - tree
      - unzip
      - yt-dlp
      - zip

        # Package management
      - pacman-contrib
      - reflector

        # Startup
      - xorg-xinit
      - xorg-xrdb
      - xorg-xmodmap

        # Shell env
      - alacritty
      - fish
      - fisher
      - vim

        # Window manager
      - arandr
      - autorandr
      - dmenu
      - i3-wm
      - polybar
    state: present

- name: Packages | AUR | Install paru
  become: false
  kewlfft.aur.aur:
    name: paru
    state: present
    use: makepkg

- name: Packages | AUR | Install
  become: false
  kewlfft.aur.aur:
    use: paru
    name:
      - insync
      - spotify
