---

- name: Sound | Installation
  become: true
  ansible.builtin.package:
    name:
      - alsa-utils
      - pulseaudio-alsa
      - pulsemixer
    state: present

- name: Sound | Add user to group audio
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - audio
    append: true

- name: Sound | Alsa | Copy configuration
  become: true
  ansible.builtin.template:
    src: files/etc_modprobe.d_alsa-base.conf.j2
    dest: /etc/modprobe.d/alsa-base.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - Common | Restart is required
