---

- name: Wireshark | Install
  ansible.builtin.package:
    name:
      - wireshark-qt

- name: Wireshark | Add user to group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - wireshark
    append: true
