---

- name: XDG user directories | Create config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/"
    state: directory
    mode: "0740"

- name: XDG user directories | Create configuration file
  ansible.builtin.copy:
    src: home_dotconfig_user-dirs.dirs
    dest: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
    mode: "0640"

- name: XDG user directories | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0740"
  with_items: "{{ lookup('file', ansible_user_dir ~ '/.config/user-dirs.dirs').splitlines() | map('regex_search', '.*=\"(.*)\"', '\\1') | flatten }}"

- name: XDG user directories | Install needed packages
  become: true
  ansible.builtin.package:
    name: xdg-user-dirs
    state: present
