---

- name: YubiKey | Install requirements
  become: true
  ansible.builtin.package:
    name:
      - libfido2
      - pam-u2f
      - yubikey-manager
    state: present
  notify:
    - Pcsc | Restart service
