---

- name: Chrome | Configure default extensions
  become: yes
  copy:
    content: "{ \"external_update_url\": \"https://clients2.google.com/service/update2/crx\" }"
    dest: "/opt/google/chrome/default_apps/{{ item }}.json"
  with_items:
    - gcbommkclmclpchllfjekcdonpmejbdp # HTTPS Everywhere
    - pkehgijcmpdhfbdbbnkijodmdjhbjlgp # Privacy Badger
    - cjpalhdlnbpafiamejdnhcphjbkeiagm # uBlock Origin
    - mfidmkgnfgnkihnjeklbekckimkipmoe # Flashcontrol
    - eiadekoaikejlgdbkbdfeijglgfdalml # WebRTC Leak Prevent
    - dbepggeogbaibhgnhhndojpepiihcmeb # Vimium
