---


- name: Fonts | Set lat1-16 as default font in /etc/vconsole.conf
  become: yes
  lineinfile:
    dest: /etc/vconsole.conf
    regexp: "^FONT="
    line: "FONT=lat1-16"
    create: yes

- name: Xorg | Add Intel Conf
  become: yes
  file:
    src: ./files/xorg/20-intel.conf
    dest: /etc/X11/xorg.conf.d/20-intel.conf
    state: link
    force: yes

- name: Alsa | Copy the Modprobe configuration file
  become: yes
  file:
    src: ./files/alsa/alsa-base.conf
    dest: /etc/modprobe.d/alsa-base.conf
    state: link
    force: yes
