---

- name: Link wpa_supplicant hook for Dhcpcd
  become: yes
  file:
    src: "/usr/share/dhcpcd/hooks/10-wpa_supplicant"
    dest: "/usr/lib/dhcpcd/dhcpcd-hooks/10-wpa_supplicant"
    state: link

- name: Link user files
  become: yes
  file:
    src: "{{ item | realpath }}"
    dest: "/etc/wpa_supplicant/{{ item | basename }}"
    state: link
  with_fileglob: "wpa_supplicant/*"
