name: Linters
on:
  - push
jobs:
  Ansible-Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install Python dependencies
        run: uv sync --locked --all-extras --dev

      - name: Install Ansible dependencies
        run: uv run ansible-galaxy collection install -r ansible-galaxy-requirements.yml

      - name: Run Linter
        run: uv run ansible-lint setup.yml -vv

      - name: Run Ansible Syntax Check
        run: uv run ./setup.yml --syntax-check -vvvv
