name: Linters
on:
  - push
jobs:
  Ansible-Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

        # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Python dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --dev

      - name: Install Ansible Collections
        run: pipenv run ansible-galaxy collection install --requirements-file ansible-galaxy-requirements.yml

      - name: Run Linter
        run: pipenv run ansible-lint setup.yml -vv

      - name: Run Ansible Syntax Check
        run: pipenv run ./setup.yml --syntax-check -vvvv
